name: GooseAPI
targets:
  GooseAPI:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [GooseAPI]
    info:
      path: ./Info.plist
      version: 1.9.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
