"""add tool call log table

Revision ID: d84f9f8eabb2
Revises: 29198b498f92
Create Date: 2025-10-07 17:03:59.070242+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd84f9f8eabb2'
down_revision: Union[str, None] = '29198b498f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_tool_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=512), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('bundle_name', sa.String(length=512), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_name', sa.String(length=512), nullable=True),
    sa.Column('mcp_server_id', sa.UUID(), nullable=True),
    sa.Column('mcp_tool_name', sa.String(length=512), nullable=True),
    sa.Column('mcp_tool_id', sa.UUID(), nullable=True),
    sa.Column('mcp_server_configuration_name', sa.String(length=512), nullable=True),
    sa.Column('mcp_server_configuration_id', sa.UUID(), nullable=True),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', name='mcptoolcallstatus', native_enum=False, length=50), nullable=False),
    sa.Column('via_execute_tool', sa.Boolean(), nullable=False),
    sa.Column('jsonrpc_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_tool_call_logs')
    # ### end Alembic commands ###
