/**
 * GenerativePanel — Renders AI-generated UI specs using json-render
 *
 * This component takes a JSON spec (generated by AI from the Goose catalog)
 * and renders it as a native React UI with charts, tables, metrics, etc.
 */
import { useState, useCallback } from 'react';
import {
  Renderer,
  StateProvider,
  ActionProvider,
  VisibilityProvider,
} from '@json-render/react';
import { registry } from '../../lib/generative-registry';
import { ElementErrorBoundary } from '../ui/design-system/ElementErrorBoundary';
import { useNavigate } from 'react-router-dom';
import { X, Maximize2, Minimize2 } from 'lucide-react';

interface GenerativePanelProps {
  /** The JSON spec to render */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  spec: any;
  /** Whether the spec is still streaming */
  isStreaming?: boolean;
  /** Initial state data for the rendered UI */
  initialState?: Record<string, unknown>;
  /** Called when user dismisses the panel */
  onDismiss?: () => void;
  /** Panel title */
  title?: string;
  /** Render mode */
  mode?: 'panel' | 'inline' | 'fullscreen';
}

export default function GenerativePanel({
  spec,
  isStreaming = false,
  initialState = {},
  onDismiss,
  title,
  mode = 'panel',
}: GenerativePanelProps) {
  const navigate = useNavigate();
  const [isExpanded, setIsExpanded] = useState(mode === 'fullscreen');

  const actionHandlers = useCallback(() => ({
    navigate: (params: Record<string, unknown>) => {
      navigate(String(params.path || '/'));
      onDismiss?.();
    },
    create_session: () => {
      window.dispatchEvent(new CustomEvent('PROMPT_BAR_SUBMIT', {
        detail: { message: '' },
      }));
      onDismiss?.();
    },
    run_eval: (params: Record<string, unknown>) => {
      navigate(`/analytics?tab=runs&dataset=${params.datasetId}`);
      onDismiss?.();
    },
    open_session: (params: Record<string, unknown>) => {
      navigate(`/pair?sessionId=${params.sessionId}`);
      onDismiss?.();
    },
    install_extension: () => {
      navigate('/extensions');
      onDismiss?.();
    },
    run_recipe: (params: Record<string, unknown>) => {
      navigate(`/recipes?run=${params.recipeId}`);
      onDismiss?.();
    },
    dismiss: () => {
      onDismiss?.();
    },
  }), [navigate, onDismiss]);

  if (!spec) return null;

  const containerClasses = isExpanded
    ? 'fixed inset-4 z-50 bg-zinc-900 border border-zinc-700 rounded-2xl shadow-2xl overflow-auto'
    : mode === 'inline'
      ? 'bg-zinc-800/30 border border-zinc-700/50 rounded-xl overflow-hidden'
      : 'bg-zinc-900 border border-zinc-700 rounded-2xl shadow-xl overflow-hidden max-h-[70vh] overflow-y-auto';

  return (
    <div className={containerClasses}>
      {(title || onDismiss) && (
        <div className="flex items-center justify-between px-4 py-3 border-b border-zinc-700/50 bg-zinc-800/50 sticky top-0 z-10">
          <div className="flex items-center gap-2">
            {isStreaming && (
              <div className="w-2 h-2 rounded-full bg-blue-400 animate-pulse" />
            )}
            <span className="text-sm font-medium text-zinc-200">
              {title || 'Generated View'}
            </span>
          </div>
          <div className="flex items-center gap-1">
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="p-1.5 rounded-md hover:bg-zinc-700 text-zinc-400 hover:text-zinc-200 transition-colors"
            >
              {isExpanded ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
            </button>
            {onDismiss && (
              <button
                onClick={onDismiss}
                className="p-1.5 rounded-md hover:bg-zinc-700 text-zinc-400 hover:text-zinc-200 transition-colors"
              >
                <X size={14} />
              </button>
            )}
          </div>
        </div>
      )}

      <div className="p-4">
        <ElementErrorBoundary elementId="GenerativePanel:root">
          <StateProvider initialState={initialState}>
            <VisibilityProvider>
              {/* @ts-ignore — json-render handlers type expects exact signature */}
              <ActionProvider handlers={actionHandlers()}>
                {/* @ts-ignore — json-render Spec type and registry type from zod 3/4 mismatch */}
                <Renderer
                  spec={spec}
                  registry={registry}
                  loading={isStreaming}
                />
              </ActionProvider>
            </VisibilityProvider>
          </StateProvider>
        </ElementErrorBoundary>
      </div>

      {isExpanded && (
        <div
          className="fixed inset-0 bg-black/50 z-40"
          onClick={() => setIsExpanded(false)}
        />
      )}
    </div>
  );
}
