[project]
name = "langfuse-wrapper"
version = "0.1.0"
description = "A wrapper for Langfuse integration"
readme = "README.md"
requires-python = ">=3.10"
author = [{ name = "Block", email = "ai-oss-tools@block.xyz" }]
packages = [{ include = "langfuse_wrapper", from = "src" }]

dependencies = [
    "langfuse>=2.38.2",
    "python-dotenv>=1.0.1"
]

[tool.hatch.build.targets.wheel]
packages = ["src/langfuse_wrapper"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["pytest>=8.3.2"]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests that need to authenticate (deselect with '-m \"not integration\"')",
]
