# Reconcile Home Manager-managed goose state idempotently.
# Invoked by the activation hook as: python manage-state.py <spec> <state>
import json
import pathlib
import shlex
import sys

spec = json.loads(pathlib.Path(sys.argv[1]).read_text())
state_path = pathlib.Path(sys.argv[2])
state_path.parent.mkdir(parents=True, exist_ok=True)

old_state = {}
if state_path.exists():
    try:
        old_state = json.loads(state_path.read_text())
    except Exception:
        old_state = {}

def strip_trailing_newline(text: str) -> str:
    return text[:-1] if text.endswith("\n") else text

def cleanup_file(path: pathlib.Path) -> None:
    try:
        if path.is_symlink() or path.is_file():
            path.unlink()
        elif path.is_dir():
            for child in path.iterdir():
                if child.is_symlink() or child.is_file():
                    child.unlink()
                elif child.is_dir():
                    cleanup_file(child)
            path.rmdir()
    except FileNotFoundError:
        pass
    except OSError:
        pass

def atomic_write_file(target: pathlib.Path, source: pathlib.Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink() or (target.exists() and not target.is_file()):
        cleanup_file(target)

    tmp = target.with_name(target.name + ".tmp")
    cleanup_file(tmp)
    tmp.write_bytes(source.read_bytes())
    tmp.replace(target)

old_config_dir = pathlib.Path(old_state.get("configDir", spec["configDir"]))
old_paths = set(old_state.get("managedPaths", []))
new_paths = set(spec["immutableFiles"].keys()) | set(spec["editableFiles"].keys())
private_paths = []
if spec["managedSecretFiles"]:
    private_paths.append("secrets.yaml")
if spec["managedEnvironmentSecretFiles"]:
    private_paths.append(spec["environmentSecretFileName"])
new_paths.update(private_paths)

stale_paths = old_paths - new_paths
if old_config_dir != pathlib.Path(spec["configDir"]):
    stale_paths |= old_paths

for relpath in stale_paths:
    cleanup_file(old_config_dir / relpath)

config_dir = pathlib.Path(spec["configDir"])
config_dir.mkdir(parents=True, exist_ok=True)

for relpath, source in spec["immutableFiles"].items():
    target = config_dir / relpath
    target.parent.mkdir(parents=True, exist_ok=True)
    cleanup_file(target)
    target.symlink_to(pathlib.Path(source))

for relpath, source in spec["editableFiles"].items():
    atomic_write_file(config_dir / relpath, pathlib.Path(source))

secrets_path = config_dir / "secrets.yaml"
if spec["managedSecretFiles"]:
    secrets = {}
    for key, source in spec["managedSecretFiles"].items():
        secrets[key] = strip_trailing_newline(pathlib.Path(source).read_text())
    tmp = secrets_path.with_name(secrets_path.name + ".tmp")
    tmp.write_text(json.dumps(secrets, indent=2, sort_keys=True) + "\n")
    tmp.chmod(0o600)
    tmp.replace(secrets_path)
else:
    cleanup_file(secrets_path)

env_path = config_dir / spec["environmentSecretFileName"]
if spec["managedEnvironmentSecretFiles"]:
    lines = ["# Generated by Home Manager; do not edit."]
    for key, source in sorted(spec["managedEnvironmentSecretFiles"].items()):
        value = strip_trailing_newline(pathlib.Path(source).read_text())
        lines.append(f"export {key}={shlex.quote(value)}")
    tmp = env_path.with_name(env_path.name + ".tmp")
    tmp.write_text("\n".join(lines) + "\n")
    tmp.chmod(0o600)
    tmp.replace(env_path)
else:
    cleanup_file(env_path)

permissions_dir = config_dir / "permissions"
if permissions_dir.is_symlink() or (permissions_dir.exists() and not permissions_dir.is_dir()):
    cleanup_file(permissions_dir)
permissions_dir.mkdir(parents=True, exist_ok=True)

state = {
    "configDir": spec["configDir"],
    "managedPaths": sorted(new_paths),
}
tmp_state = state_path.with_name(state_path.name + ".tmp")
tmp_state.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
tmp_state.replace(state_path)
