name: Hacktobefest Content
title: "Hacktoberfest Blog: <add your title here>"
labels: ["hacktoberfest", "hacktoberfest-accepted"]
assignees: ["ebonylouis", "blackgirlbytes", "taniandjerry"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description

  - type: input
    id: url
    attributes:
      label: URL

  - type: dropdown
    id: kind
    attributes:
      label: Type
      options:
        - Blog post
        - YouTube video

  - type: checkboxes
    id: public
    attributes:
      label: Confirmation
      options:
        - label: My submission is publicly accessible right now.
