authors:
  ebony:
    name: Ebony Louis
    description: Developer Advocate
    avatar: https://avatars.githubusercontent.com/u/55366651?v=4
  rizel:
    name: Rizel Scarlett
    description: Staff Developer Advocate
    avatar: https://avatars.githubusercontent.com/u/22990146?v=4
  adewale:
    name: Adewale Abati
    description: Staff Developer Advocate
    avatar: https://avatars.githubusercontent.com/u/4003538?v=4