authors:
  ebony:
    name: Ebony Louis
    description: Developer Advocate
    avatar: https://avatars.githubusercontent.com/u/55366651?v=4
  rizel:
    name: Rizel Scarlett
    description: Staff Developer Advocate
    avatar: https://avatars.githubusercontent.com/u/22990146?v=4
  adewale:
    name: Adewale Abati
    description: Staff Developer Advocate
    avatar: https://avatars.githubusercontent.com/u/4003538?v=4
  dalton:
    name: Dalton Turner
    description: Software Engineer
    avatar: https://avatars.githubusercontent.com/u/78099245?v=4
  tania:
    name: Tania Chakraborty
    description: Senior Technical Community Manager
    avatar: https://avatars.githubusercontent.com/u/126204004?v=4
  angie:
    name: Angie Jones
    description: Head of Developer Relations
    avatar: https://avatars.githubusercontent.com/u/15972783?v=4     
