import type { Resource } from 'i18next';

export const resources: Resource = {
  en: {
    translation: {
      common: {
        language: 'Language',
        system: 'System',
        english: 'English',
        simplifiedChinese: '简体中文',
        traditionalChinese: '繁體中文',
      },
      onboarding: {
        welcome: {
          title: 'Welcome to Goose',
          subtitle:
            "Since it’s your first time here, let’s get you set up with an AI provider so goose can work its magic.",
          moreOptionsBelow: 'More options below',
        },
        cards: {
          runLocally: {
            title: 'Run Locally',
            description:
              'Download a model and run entirely on your machine. No API keys, no accounts.',
            badge: 'Free & Private',
          },
          chatgpt: {
            title: 'ChatGPT Subscription',
            description: 'Use your ChatGPT Plus/Pro subscription for GPT-5 Codex models.',
            badge: 'Recommended if you have ChatGPT Plus/Pro',
          },
          tetrate: {
            title: 'Agent Router',
            byline: 'by Tetrate',
            description:
              'Access multiple AI models with automatic setup. Sign up to receive $10 credit.',
            badge: 'Recommended for new users',
          },
          openrouter: {
            title: 'OpenRouter',
            description: 'Access 200+ models with one API. Pay-per-use pricing.',
          },
          otherProviders: {
            title: 'Other Providers',
            description: 'Set up additional providers manually through settings.',
            cta: 'Go to Provider Settings →',
          },
        },
        setup: {
          failed: 'Setup Failed',
          error: 'Setup Error',
          unexpectedError: 'An unexpected error occurred during setup.',
          chooseModel: 'Choose Model',
        },
      },
      providerSettings: {
        header: {
          onboarding: 'Other providers',
          settings: 'Provider Configuration Settings',
        },
        intro:
          "Select an AI model provider to get started with goose. You'll need to use API keys generated by each provider which will be encrypted and stored locally. You can change your provider at any time in settings.",
        loading: 'Loading providers...',
      },
      extensions: {
        title: 'Extensions',
        description1:
          "These extensions use the Model Context Protocol (MCP). They can expand Goose's capabilities using three main components: Prompts, Resources, and Tools.",
        description2:
          'Extensions enabled here are used as the default for new chats. You can also toggle active extensions during chat.',
        addCustom: 'Add custom extension',
        browse: 'Browse extensions',
        searchPlaceholder: 'Search extensions...',
      },
      settings: {
        title: 'Settings',
        tabs: {
          models: 'Models',
          localInference: 'Local Inference',
          chat: 'Chat',
          session: 'Session',
          prompts: 'Prompts',
          keyboard: 'Keyboard',
          app: 'App',
        },
        app: {
          appearance: {
            title: 'Appearance',
            description: 'Configure how goose appears on your system',
            notifications: 'Notifications',
            notificationsDescription: 'Notifications are managed by your OS',
            configurationGuide: 'Configuration guide',
            openSettings: 'Open Settings',
            menuBarIcon: 'Menu bar icon',
            menuBarIconDescription: 'Show goose in the menu bar',
            dockIcon: 'Dock icon',
            dockIconDescription: 'Show goose in the dock',
            preventSleep: 'Prevent Sleep',
            preventSleepDescription:
              'Keep your computer awake while goose is running a task (screen can still lock)',
            language: 'Language',
            languageDescription:
              'Use system language automatically or force a language for the interface.',
            costTracking: 'Cost Tracking',
            costTrackingDescription: 'Show model pricing and usage costs',
          },
          theme: {
            title: 'Theme',
            description: 'Customize the look and feel of goose',
          },
          navigation: {
            title: 'Navigation',
            description: 'Customize navigation layout and behavior',
            mode: 'Mode',
            style: 'Style',
            position: 'Position',
            customizeItems: 'Customize Items',
          },
          help: {
            title: 'Help & feedback',
            description: 'Help us improve goose by reporting issues or requesting new features',
            reportBug: 'Report a Bug',
            requestFeature: 'Request a Feature',
          },
          version: 'Version',
          updates: {
            title: 'Updates',
            description: 'Check for and install updates to keep goose running at its best',
          },
          notificationsModal: {
            title: 'How to Enable Notifications',
            macIntro: 'To enable notifications on macOS:',
            windowsIntro: 'To enable notifications on Windows:',
            macSteps: [
              'Open System Preferences',
              'Click on Notifications',
              'Find and select goose in the application list',
              'Enable notifications and adjust settings as desired',
            ],
            windowsSteps: [
              'Open Settings',
              'Go to System > Notifications',
              'Find and select goose in the application list',
              'Toggle notifications on and adjust settings as desired',
            ],
            close: 'Close',
          },
        },
        telemetry: {
          title: 'Privacy',
          description: 'Control how your data is used',
          anonymousUsageData: 'Anonymous usage data',
          anonymousUsageDataDescription:
            'Help improve goose by sharing anonymous usage statistics.',
          learnMore: 'Learn more',
        },
        resetProvider: {
          button: 'Reset Provider and Model',
          description:
            "This will clear your selected model and provider settings. If no defaults are available, you'll be taken to the welcome screen to set them up again.",
        },
      },
      theme: {
        light: 'Light',
        dark: 'Dark',
        system: 'System',
      },
    },
  },
  'zh-Hans': {
    translation: {
      common: {
        language: '语言',
        system: '跟随系统',
        english: 'English',
        simplifiedChinese: '简体中文',
        traditionalChinese: '繁體中文',
      },
      onboarding: {
        welcome: {
          title: '欢迎使用 goose',
          subtitle: '这是你第一次使用，我们先配置一个 AI Provider，让 goose 开始工作。',
          moreOptionsBelow: '下方还有更多选项',
        },
        cards: {
          runLocally: {
            title: '本地运行',
            description: '下载模型并完全在本机运行。无需 API Key，无需账号。',
            badge: '免费且私密',
          },
          chatgpt: {
            title: 'ChatGPT 订阅',
            description: '使用你的 ChatGPT Plus/Pro 订阅访问 GPT-5 Codex 模型。',
            badge: '如你已有 ChatGPT Plus/Pro，推荐使用',
          },
          tetrate: {
            title: 'Agent Router',
            byline: 'by Tetrate',
            description: '自动接入多个 AI 模型。注册可领取 10 美元额度。',
            badge: '新用户推荐',
          },
          openrouter: {
            title: 'OpenRouter',
            description: '一个 API 访问 200+ 模型，按量计费。',
          },
          otherProviders: {
            title: '其他 Provider',
            description: '在设置中手动配置更多 Provider。',
            cta: '前往 Provider 设置 →',
          },
        },
        setup: {
          failed: '配置失败',
          error: '配置错误',
          unexpectedError: '配置过程中发生了未知错误。',
          chooseModel: '选择模型',
        },
      },
      providerSettings: {
        header: {
          onboarding: '其他 Provider',
          settings: 'Provider 配置',
        },
        intro:
          '选择一个 AI 模型 Provider 开始使用 goose。你需要使用各 Provider 生成的 API Key，这些密钥会被加密并保存在本地。你可以随时在设置中更换 Provider。',
        loading: '正在加载 Provider...',
      },
      extensions: {
        title: '扩展',
        description1:
          '这些扩展基于 MCP（Model Context Protocol），可通过 Prompts、Resources、Tools 三类能力扩展 Goose。',
        description2: '这里启用的扩展会作为新会话的默认扩展。你也可以在聊天中动态切换。',
        addCustom: '添加自定义扩展',
        browse: '浏览扩展',
        searchPlaceholder: '搜索扩展...',
      },
      settings: {
        title: '设置',
        tabs: {
          models: '模型',
          localInference: '本地推理',
          chat: '聊天',
          session: '会话',
          prompts: 'Prompts',
          keyboard: '快捷键',
          app: '应用',
        },
        app: {
          appearance: {
            title: '外观',
            description: '配置 goose 在系统中的显示方式',
            notifications: '通知',
            notificationsDescription: '通知由你的操作系统管理',
            configurationGuide: '配置指南',
            openSettings: '打开设置',
            menuBarIcon: '菜单栏图标',
            menuBarIconDescription: '在菜单栏显示 goose',
            dockIcon: 'Dock 图标',
            dockIconDescription: '在 Dock 中显示 goose',
            preventSleep: '防止休眠',
            preventSleepDescription: 'goose 执行任务时保持设备唤醒（屏幕仍可锁定）',
            language: '语言',
            languageDescription: '可跟随系统语言，或手动指定界面语言。',
            costTracking: '成本追踪',
            costTrackingDescription: '显示模型价格与调用成本',
          },
          theme: {
            title: '主题',
            description: '自定义 goose 的外观风格',
          },
          navigation: {
            title: '导航',
            description: '自定义导航布局与行为',
            mode: '模式',
            style: '样式',
            position: '位置',
            customizeItems: '自定义条目',
          },
          help: {
            title: '帮助与反馈',
            description: '通过报告问题或提出功能需求帮助我们改进 goose',
            reportBug: '报告 Bug',
            requestFeature: '功能建议',
          },
          version: '版本',
          updates: {
            title: '更新',
            description: '检查并安装更新，保持 goose 最佳状态',
          },
          notificationsModal: {
            title: '如何开启通知',
            macIntro: '在 macOS 上开启通知：',
            windowsIntro: '在 Windows 上开启通知：',
            macSteps: [
              '打开系统设置',
              '点击通知',
              '在应用列表中找到 goose',
              '开启通知并按需调整选项',
            ],
            windowsSteps: [
              '打开设置',
              '进入 系统 > 通知',
              '在应用列表中找到 goose',
              '开启通知并按需调整选项',
            ],
            close: '关闭',
          },
        },
        telemetry: {
          title: '隐私',
          description: '控制你的数据如何被使用',
          anonymousUsageData: '匿名使用数据',
          anonymousUsageDataDescription: '通过分享匿名统计信息帮助我们改进 goose。',
          learnMore: '了解更多',
        },
        resetProvider: {
          button: '重置 Provider 与模型',
          description:
            '这将清除你当前选择的模型和 Provider。若没有可用默认值，你将返回欢迎页重新配置。',
        },
      },
      theme: {
        light: '浅色',
        dark: '深色',
        system: '跟随系统',
      },
    },
  },
  'zh-Hant': {
    translation: {
      common: {
        language: '語言',
        system: '跟隨系統',
        english: 'English',
        simplifiedChinese: '简体中文',
        traditionalChinese: '繁體中文',
      },
      onboarding: {
        welcome: {
          title: '歡迎使用 goose',
          subtitle: '這是你第一次使用，我們先設定 AI Provider，讓 goose 開始工作。',
          moreOptionsBelow: '下方還有更多選項',
        },
        cards: {
          runLocally: {
            title: '本機執行',
            description: '下載模型並完全在本機執行。無需 API Key，也不需帳號。',
            badge: '免費且私密',
          },
          chatgpt: {
            title: 'ChatGPT 訂閱',
            description: '使用你的 ChatGPT Plus/Pro 訂閱存取 GPT-5 Codex 模型。',
            badge: '若你已有 ChatGPT Plus/Pro，建議使用',
          },
          tetrate: {
            title: 'Agent Router',
            byline: 'by Tetrate',
            description: '自動接入多個 AI 模型。註冊可獲得 10 美元額度。',
            badge: '新用戶推薦',
          },
          openrouter: {
            title: 'OpenRouter',
            description: '一個 API 存取 200+ 模型，按量計費。',
          },
          otherProviders: {
            title: '其他 Provider',
            description: '可在設定中手動設定更多 Provider。',
            cta: '前往 Provider 設定 →',
          },
        },
        setup: {
          failed: '設定失敗',
          error: '設定錯誤',
          unexpectedError: '設定過程中發生未知錯誤。',
          chooseModel: '選擇模型',
        },
      },
      providerSettings: {
        header: {
          onboarding: '其他 Provider',
          settings: 'Provider 設定',
        },
        intro:
          '選擇一個 AI 模型 Provider 以開始使用 goose。你需要使用各 Provider 產生的 API Key，這些金鑰會被加密並儲存在本機。你可隨時在設定中切換 Provider。',
        loading: '正在載入 Provider...',
      },
      extensions: {
        title: '擴展',
        description1:
          '這些擴展基於 MCP（Model Context Protocol），可透過 Prompts、Resources、Tools 三種能力擴充 Goose。',
        description2: '此處啟用的擴展會作為新對話預設。你也可在聊天中動態切換。',
        addCustom: '新增自訂擴展',
        browse: '瀏覽擴展',
        searchPlaceholder: '搜尋擴展...',
      },
      settings: {
        title: '設定',
        tabs: {
          models: '模型',
          localInference: '本機推理',
          chat: '聊天',
          session: '工作階段',
          prompts: 'Prompts',
          keyboard: '快捷鍵',
          app: '應用程式',
        },
        app: {
          appearance: {
            title: '外觀',
            description: '設定 goose 在系統中的顯示方式',
            notifications: '通知',
            notificationsDescription: '通知由你的作業系統管理',
            configurationGuide: '設定指南',
            openSettings: '開啟設定',
            menuBarIcon: '選單列圖示',
            menuBarIconDescription: '在選單列顯示 goose',
            dockIcon: 'Dock 圖示',
            dockIconDescription: '在 Dock 顯示 goose',
            preventSleep: '防止休眠',
            preventSleepDescription: 'goose 執行任務時保持裝置喚醒（螢幕仍可鎖定）',
            language: '語言',
            languageDescription: '可跟隨系統語言，或手動指定介面語言。',
            costTracking: '成本追蹤',
            costTrackingDescription: '顯示模型價格與使用成本',
          },
          theme: {
            title: '主題',
            description: '自訂 goose 的外觀風格',
          },
          navigation: {
            title: '導覽',
            description: '自訂導覽版面與行為',
            mode: '模式',
            style: '樣式',
            position: '位置',
            customizeItems: '自訂項目',
          },
          help: {
            title: '協助與回饋',
            description: '透過回報問題或提出需求，協助我們改進 goose',
            reportBug: '回報 Bug',
            requestFeature: '功能建議',
          },
          version: '版本',
          updates: {
            title: '更新',
            description: '檢查並安裝更新，讓 goose 維持最佳狀態',
          },
          notificationsModal: {
            title: '如何啟用通知',
            macIntro: '在 macOS 啟用通知：',
            windowsIntro: '在 Windows 啟用通知：',
            macSteps: [
              '開啟系統設定',
              '點選通知',
              '在應用程式清單中找到 goose',
              '啟用通知並依需求調整',
            ],
            windowsSteps: [
              '開啟設定',
              '進入 系統 > 通知',
              '在應用程式清單中找到 goose',
              '啟用通知並依需求調整',
            ],
            close: '關閉',
          },
        },
        telemetry: {
          title: '隱私',
          description: '控制你的資料如何被使用',
          anonymousUsageData: '匿名使用資料',
          anonymousUsageDataDescription: '分享匿名統計資料，幫助我們改進 goose。',
          learnMore: '了解更多',
        },
        resetProvider: {
          button: '重設 Provider 與模型',
          description:
            '這會清除你目前選擇的模型與 Provider。若沒有可用預設值，你將回到歡迎頁重新設定。',
        },
      },
      theme: {
        light: '淺色',
        dark: '深色',
        system: '跟隨系統',
      },
    },
  },
};
