//! Optional runtime refresh of the canonical model registry.
//!
//! By default goose relies entirely on the registry embedded in the binary at
//! build time. When [`is_enabled`] returns true (via `GOOSE_CANONICAL_DYNAMIC`),
//! goose will additionally fetch the latest published canonical inventory, cache
//! it to disk, and merge it over the bundled data so newly released models are
//! picked up without a code change or a new release.
//!
//! The published inventory is the flat `Vec<CanonicalModel>` produced by the
//! offline builder and served from a stable URL (e.g. GitHub Pages). Because it
//! is generated by goose's own pipeline it already reflects curated overrides
//! and variant-collision resolution — the runtime just fetches and parses it.
//!
//! The cache is a plain JSON file with a fetch timestamp. On access the registry
//! layer loads it (if present) and, when stale, triggers a background refresh so
//! the current call is never blocked on the network.

use super::source::{self, CANONICAL_MODELS_URL};
use super::{CanonicalModel, CanonicalModelRegistry};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// Enable dynamic fetching of canonical model data.
const ENV_ENABLE: &str = "GOOSE_CANONICAL_DYNAMIC";
/// Override the refresh interval, in seconds. Defaults to [`DEFAULT_REFRESH_SECS`].
const ENV_REFRESH_SECS: &str = "GOOSE_CANONICAL_REFRESH_SECS";
/// Override the inventory source URL. Defaults to [`CANONICAL_MODELS_URL`].
const ENV_SOURCE_URL: &str = "GOOSE_CANONICAL_SOURCE_URL";
/// Test/isolation hook mirroring goose's `Paths` behaviour.
const ENV_PATH_ROOT: &str = "GOOSE_PATH_ROOT";

const DEFAULT_REFRESH_SECS: u64 = 24 * 60 * 60;
const CACHE_FILE: &str = "canonical_models_cache.json";

/// Whether dynamic refresh is enabled. Off unless explicitly opted in.
pub fn is_enabled() -> bool {
    matches!(
        std::env::var(ENV_ENABLE).ok().as_deref(),
        Some("1" | "true" | "TRUE" | "yes")
    )
}

/// Refresh interval in seconds.
pub fn refresh_secs() -> u64 {
    std::env::var(ENV_REFRESH_SECS)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(DEFAULT_REFRESH_SECS)
}

/// Inventory source URL.
pub fn source_url() -> String {
    std::env::var(ENV_SOURCE_URL).unwrap_or_else(|_| CANONICAL_MODELS_URL.to_string())
}

/// Location of the on-disk cache.
///
/// Honors `GOOSE_PATH_ROOT` (used by tests) and otherwise falls back to the
/// platform cache dir. `goose-provider-types` cannot depend on the `goose`
/// crate's `Paths`, so the resolution is intentionally standalone but mirrors it.
pub fn cache_path() -> PathBuf {
    if let Ok(root) = std::env::var(ENV_PATH_ROOT) {
        return PathBuf::from(root).join("cache").join(CACHE_FILE);
    }

    let base = etcetera::choose_base_strategy()
        .ok()
        .map(|s| {
            use etcetera::BaseStrategy;
            s.cache_dir()
        })
        .unwrap_or_else(std::env::temp_dir);

    base.join("goose").join(CACHE_FILE)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct CacheFile {
    fetched_at: u64,
    models: Vec<CanonicalModel>,
}

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Load the cached registry from disk, if present and parseable, along with its
/// staleness relative to [`refresh_secs`].
pub fn load_cached() -> Option<(CanonicalModelRegistry, bool)> {
    let path = cache_path();
    let content = std::fs::read_to_string(&path).ok()?;
    let cache: CacheFile = serde_json::from_str(&content).ok()?;

    let mut registry = CanonicalModelRegistry::new();
    for model in cache.models {
        if let Some((provider, model_name)) = model.id.split_once('/') {
            registry.register(provider, model_name, model.clone());
        }
    }

    let age = now_secs().saturating_sub(cache.fetched_at);
    let stale = age >= refresh_secs();
    Some((registry, stale))
}

fn write_cache(models: &[&CanonicalModel]) -> Result<()> {
    let path = cache_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).context("Failed to create cache directory")?;
    }

    let cache = CacheFile {
        fetched_at: now_secs(),
        models: models.iter().map(|m| (*m).clone()).collect(),
    };

    let json = serde_json::to_string(&cache).context("Failed to serialize cache")?;
    std::fs::write(&path, json).context("Failed to write cache file")?;
    Ok(())
}

/// Fetch the latest inventory from the source, build a registry, and write it to
/// the on-disk cache. Returns the freshly built registry.
pub async fn refresh() -> Result<CanonicalModelRegistry> {
    let json = source::fetch_canonical_json(&source_url()).await?;
    let registry = source::registry_from_canonical_json(&json)?;
    write_cache(&registry.all_models())?;
    Ok(registry)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canonical::{Limit, Modalities, Pricing};

    fn sample_model(id: &str) -> CanonicalModel {
        CanonicalModel {
            id: id.to_string(),
            name: id.to_string(),
            family: None,
            attachment: None,
            reasoning: Some(true),
            thinking_mode: None,
            tool_call: true,
            temperature: Some(false),
            knowledge: None,
            release_date: None,
            last_updated: None,
            modalities: Modalities::default(),
            open_weights: None,
            cost: Pricing::default(),
            limit: Limit::default(),
        }
    }

    fn write_cache_file(root: &std::path::Path, fetched_at: u64, models: Vec<CanonicalModel>) {
        let cache = CacheFile { fetched_at, models };
        let path = root.join("cache").join(CACHE_FILE);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, serde_json::to_string(&cache).unwrap()).unwrap();
    }

    #[test]
    fn is_enabled_defaults_off() {
        let _guard = env_lock::lock_env([(ENV_ENABLE, None::<&str>)]);
        assert!(!is_enabled());
    }

    #[test]
    fn is_enabled_respects_truthy_values() {
        for val in ["1", "true", "TRUE", "yes"] {
            let _guard = env_lock::lock_env([(ENV_ENABLE, Some(val))]);
            assert!(is_enabled(), "{val} should enable");
        }
        let _guard = env_lock::lock_env([(ENV_ENABLE, Some("0"))]);
        assert!(!is_enabled());
    }

    #[test]
    fn refresh_secs_defaults_and_overrides() {
        {
            let _guard = env_lock::lock_env([(ENV_REFRESH_SECS, None::<&str>)]);
            assert_eq!(refresh_secs(), DEFAULT_REFRESH_SECS);
        }
        let _guard = env_lock::lock_env([(ENV_REFRESH_SECS, Some("60"))]);
        assert_eq!(refresh_secs(), 60);
    }

    #[test]
    fn load_cached_reports_fresh_and_stale() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        let _guard = env_lock::lock_env([
            (ENV_PATH_ROOT, Some(root.to_str().unwrap())),
            (ENV_REFRESH_SECS, Some("3600")),
        ]);

        // Fresh cache (fetched now).
        write_cache_file(root, now_secs(), vec![sample_model("x-ai/grok-4.5")]);
        let (registry, stale) = load_cached().expect("cache should load");
        assert!(!stale, "recent cache should be fresh");
        assert!(registry.get("x-ai", "grok-4.5").is_some());

        // Stale cache (fetched well beyond the interval).
        write_cache_file(
            root,
            now_secs().saturating_sub(7200),
            vec![sample_model("x-ai/grok-4.5")],
        );
        let (_, stale) = load_cached().expect("cache should load");
        assert!(stale, "old cache should be stale");
    }

    #[test]
    fn load_cached_absent_returns_none() {
        let tmp = tempfile::tempdir().unwrap();
        let _guard = env_lock::lock_env([(ENV_PATH_ROOT, Some(tmp.path().to_str().unwrap()))]);
        assert!(load_cached().is_none());
    }

    #[tokio::test]
    async fn refresh_fetches_parses_and_caches() {
        use wiremock::matchers::{method, path};
        use wiremock::{Mock, MockServer, ResponseTemplate};

        let server = MockServer::start().await;
        let body = serde_json::to_string(&vec![sample_model("x-ai/grok-4.5")]).unwrap();
        Mock::given(method("GET"))
            .and(path("/canonical_models.json"))
            .respond_with(ResponseTemplate::new(200).set_body_string(body))
            .mount(&server)
            .await;

        let tmp = tempfile::tempdir().unwrap();
        let url = format!("{}/canonical_models.json", server.uri());
        let _guard = env_lock::lock_env([
            (ENV_PATH_ROOT, Some(tmp.path().to_str().unwrap())),
            (ENV_SOURCE_URL, Some(url.as_str())),
        ]);

        // The published inventory is fetched over HTTP, parsed, and returned...
        let registry = refresh().await.expect("refresh should succeed");
        let model = registry.get("x-ai", "grok-4.5").expect("model present");
        assert_eq!(model.reasoning, Some(true));
        assert_eq!(model.temperature, Some(false));

        // ...and written to the on-disk cache so subsequent loads are offline.
        let (cached, stale) = load_cached().expect("cache should have been written");
        assert!(!stale);
        assert!(cached.get("x-ai", "grok-4.5").is_some());
    }
}
