# Example Goose Configuration with Lead Model Support
# This file should be placed at ~/.config/goose/config.yaml

# Standard provider configuration (backward compatible)
GOOSE_PROVIDER: openai
GOOSE_MODEL: gpt-4o-mini

# Option 1: Simple lead model setup (just add GOOSE_LEAD_MODEL)
# GOOSE_LEAD_MODEL: gpt-4o

# Option 2: Advanced Lead Model configuration (optional)
# This section enables intelligent model switching with full control
lead_model:
  enabled: true
  
  # Lead model configuration (for initial turns and fallback)
  lead_provider: openai      # Optional: defaults to main provider
  lead_model: gpt-4o         # Required when enabled
  
  # Behavior settings
  lead_turns: 3              # Number of initial turns using lead model
  failure_threshold: 2       # Consecutive failures before fallback
  fallback_turns: 2          # Number of turns to use lead model in fallback

# Alternative configurations:

# Same provider, different models (cost optimization)
# lead_model:
#   enabled: true
#   lead_model: gpt-4o
#   # Uses same provider (openai) for both, worker model is gpt-4o-mini

# Cross-provider setup (best of both worlds)
# lead_model:
#   enabled: true
#   lead_provider: anthropic
#   lead_model: claude-3-5-sonnet-20241022
#   # Worker uses openai/gpt-4o-mini from main config

# Minimal setup (just enable with lead model)
# lead_model:
#   enabled: true
#   lead_model: gpt-4o
#   # Everything else uses defaults