#!/usr/bin/env bash
# Prepare ui/desktop/.env for local goose serve + avocado provider OAuth.
# No gateway / Electron LoginGuard — identity lives on the avocado provider.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${PREPARE_DEV_UI_ENV_FILE:-${ROOT}/ui/desktop/.env}"
SECRET="${GOOSE_SERVER__SECRET_KEY:-avcd-agent-local-development-key}"
AVOCADO_HOST="${AVOCADO_HOST:-https://dev.avocado.tech/llm}"
DEFAULT_MODEL="${GOOSE_DEFAULT_MODEL:-anthropic/claude-sonnet-4.6}"

if [[ "'" == *"${SECRET}"* ]] || [[ "${SECRET}" == *$'\n'* ]]; then
  echo "server secret cannot be encoded safely in dotenv" >&2
  exit 1
fi

# Predefined models for avocado (LiteLLM / OpenRouter-backed catalog on the host).
MODELS_JSON='[{"name":"anthropic/claude-sonnet-4.6","provider":"avocado","alias":"Claude Sonnet 4.6","subtext":"Avocado billed"},{"name":"anthropic/claude-opus-4.1","provider":"avocado","alias":"Claude Opus 4.1","subtext":"Avocado billed"},{"name":"openai/gpt-4.1","provider":"avocado","alias":"GPT-4.1","subtext":"Avocado billed"},{"name":"google/gemini-2.5-pro","provider":"avocado","alias":"Gemini 2.5 Pro","subtext":"Avocado billed"}]'

cat > "${ENV_FILE}" <<EOF
# Generated by make dev-ui — local goose serve + avocado provider OAuth.
# Sign in is handled by the avocado provider (Zitadel PKCE → /llm-api/keys/provision).
# Do not set GOOSE_EXTERNAL_BACKEND — packaged/dev desktop uses local goose.
GOOSE_SERVER__SECRET_KEY='${SECRET}'
GOOSE_MODE=smart_approve
GOOSE_OAUTH_CALLBACK_PORT=18787
GOOSE_DEFAULT_PROVIDER=avocado
GOOSE_DEFAULT_MODEL=${DEFAULT_MODEL}
GOOSE_PREDEFINED_MODELS='${MODELS_JSON}'
AVOCADO_HOST=${AVOCADO_HOST}
EOF

echo "Wrote ${ENV_FILE} for local goose + avocado provider OAuth (no gateway)"
