#!/usr/bin/env bash
# Prepare ui/desktop/.env for local goose serve + avocado provider OAuth.
# No gateway / Electron LoginGuard — identity lives on the avocado provider.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${PREPARE_DEV_UI_ENV_FILE:-${ROOT}/ui/desktop/.env}"
CATALOG="${ROOT}/config/avcd-openrouter-models.json"
SECRET="${GOOSE_SERVER__SECRET_KEY:-avcd-agent-local-development-key}"
HOSTED_HOST="https://dev.avocado.tech/llm"
HOSTED_PROVISION="https://dev.avocado.tech/llm-api/keys/provision"
LOCAL_API="http://127.0.0.1:3001"
LOCAL_LLM="http://127.0.0.1:4000"

if [[ "'" == *"${SECRET}"* ]] || [[ "${SECRET}" == *$'\n'* ]]; then
  echo "server secret cannot be encoded safely in dotenv" >&2
  exit 1
fi

local_api_healthy() {
  curl -sf --max-time 1 "${LOCAL_API}/health" 2>/dev/null | grep -q '"status"'
}

local_llm_healthy() {
  curl -sf --max-time 1 "${LOCAL_LLM}/health/liveliness" >/dev/null 2>&1
}

hosted_provision_accepts_post() {
  local code
  code="$(curl -sS --max-time 3 -o /dev/null -w '%{http_code}' -X POST "${HOSTED_PROVISION}" \
    -H 'Authorization: Bearer probe' -H 'Accept: application/json' 2>/dev/null || echo 000)"
  # avcd-llm maps a junk token to 401 JSON. nginx/landing-page returns 405 HTML.
  [[ "${code}" == "401" || "${code}" == "403" || "${code}" == "200" ]]
}

USER_SET_PROVISION="${AVOCADO_PROVISION_URL:-}"
USER_SET_HOST="${AVOCADO_HOST:-}"

if [[ -n "${USER_SET_PROVISION}" ]]; then
  AVOCADO_PROVISION_URL="${USER_SET_PROVISION}"
  AVOCADO_HOST="${USER_SET_HOST:-${HOSTED_HOST}}"
elif local_api_healthy; then
  AVOCADO_PROVISION_URL="${LOCAL_API}/keys/provision"
  if local_llm_healthy; then
    AVOCADO_HOST="${LOCAL_LLM}"
  elif [[ -n "${USER_SET_HOST}" ]]; then
    AVOCADO_HOST="${USER_SET_HOST}"
  else
    AVOCADO_HOST="${HOSTED_HOST}"
    echo "Local LiteLLM on :4000 is down — provision keys from :3001 will not work against ${AVOCADO_HOST}." >&2
  fi
  echo "Using local avcd-llm provision at ${AVOCADO_PROVISION_URL} (host ${AVOCADO_HOST})"
  echo "Hosted ${HOSTED_PROVISION} is not routing POSTs (nginx 405 / landing page)."
elif hosted_provision_accepts_post; then
  AVOCADO_PROVISION_URL="${HOSTED_PROVISION}"
  AVOCADO_HOST="${USER_SET_HOST:-${HOSTED_HOST}}"
else
  echo "Hosted provision ${HOSTED_PROVISION} is not the avcd-llm API (expected 401, got nginx 405)." >&2
  echo "Start local avcd-llm (make -C ../avcd-llm dev) or set AVOCADO_PROVISION_URL." >&2
  AVOCADO_PROVISION_URL="${HOSTED_PROVISION}"
  AVOCADO_HOST="${USER_SET_HOST:-${HOSTED_HOST}}"
fi

CATALOG_PROVIDER="$(
  python3 - "${CATALOG}" <<'PY'
import json, sys
from pathlib import Path
print(json.loads(Path(sys.argv[1]).read_text())["provider"])
PY
)"
CATALOG_DEFAULT_MODEL="$(
  python3 - "${CATALOG}" <<'PY'
import json, sys
from pathlib import Path
print(json.loads(Path(sys.argv[1]).read_text())["defaultModel"])
PY
)"
MODELS_JSON="$(
  python3 - "${CATALOG}" <<'PY'
import json, sys
from pathlib import Path
catalog = json.loads(Path(sys.argv[1]).read_text())
predefined = [
    {
        "name": model["name"],
        "provider": catalog["provider"],
        "alias": model["alias"],
        "subtext": model["subtext"],
    }
    for model in catalog["models"]
]
print(json.dumps(predefined, separators=(",", ":")))
PY
)"
DEFAULT_MODEL="${GOOSE_DEFAULT_MODEL:-${CATALOG_DEFAULT_MODEL}}"

cat > "${ENV_FILE}" <<EOF
# Generated by make dev-ui — local goose serve + avocado provider OAuth.
# Sign in: avocado provider (Zitadel PKCE → AVOCADO_PROVISION_URL).
# Do not set GOOSE_EXTERNAL_BACKEND — packaged/dev desktop uses local goose.
GOOSE_SERVER__SECRET_KEY='${SECRET}'
GOOSE_MODE=smart_approve
GOOSE_OAUTH_CALLBACK_PORT=18787
GOOSE_DEFAULT_PROVIDER=${CATALOG_PROVIDER}
GOOSE_DEFAULT_MODEL=${DEFAULT_MODEL}
GOOSE_PREDEFINED_MODELS='${MODELS_JSON}'
AVOCADO_HOST=${AVOCADO_HOST}
AVOCADO_PROVISION_URL=${AVOCADO_PROVISION_URL}
EOF

echo "Wrote ${ENV_FILE}"
echo "  AVOCADO_PROVISION_URL=${AVOCADO_PROVISION_URL}"
echo "  AVOCADO_HOST=${AVOCADO_HOST}"
