// This file is auto-generated by @hey-api/openapi-ts
export * from './types.gen';
export * from './sdk.gen';

import {client} from './client.gen';

function configureRequest(request: Request) {
    request.headers.append('X-Secret-Key', '');
    return request;
}

client.interceptors.request.use(configureRequest)