#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src" / "components"
OUT = Path(__file__).resolve().parents[1] / "docs" / "atomic-design-inventory.md"


def classify(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()

    # Explicit directories (current project structure)
    if rel.startswith("pages/"):
        return "Pages"
    if rel.startswith("Layout/"):
        return "Templates"
    if rel.startswith("ui/atoms/"):
        return "Atoms"
    if rel.startswith("ui/molecules/"):
        return "Molecules"
    if rel.startswith("ui/design-system/"):
        # Reusable DS components are closer to molecules by default.
        return "Molecules"

    # Everything else is currently feature UI living under components/<feature>/...
    return "Organisms"


def main() -> None:
    files = sorted([p for p in ROOT.rglob("*") if p.suffix in (".ts", ".tsx")])
    by: dict[str, list[Path]] = {k: [] for k in ["Atoms", "Molecules", "Organisms", "Templates", "Pages"]}

    for p in files:
        by[classify(p)].append(p)

    lines: list[str] = []
    lines.append("# Atomic Design inventory (draft)")
    lines.append("")
    lines.append("This file is auto-generated by `ui/desktop/scripts/generate-atomic-inventory.py`.")
    lines.append("")
    lines.append("## Definitions (Brad Frost, Chapter 2)")
    lines.append("")
    lines.append("- **Atoms**: smallest functional UI building blocks (e.g., button, input, label, icon).")
    lines.append("- **Molecules**: small groups of atoms that work together as a unit (e.g., labeled input, dropdown, data table).")
    lines.append("- **Organisms**: assemblies of molecules that form distinct sections of an interface (e.g., sidebar, instance list, settings panel).")
    lines.append("- **Templates**: page-level layout scaffolding that wires regions but uses placeholders for content.")
    lines.append("- **Pages**: concrete instances of templates with real content and data.")
    lines.append("")
    lines.append("## Totals")
    lines.append("")
    for k in ["Atoms", "Molecules", "Organisms", "Templates", "Pages"]:
        lines.append(f"- **{k}**: {len(by[k])}")
    lines.append("")

    for k in ["Atoms", "Molecules", "Organisms", "Templates", "Pages"]:
        lines.append(f"## {k}")
        lines.append("")
        for p in by[k]:
            rel = p.relative_to(ROOT).as_posix()
            lines.append(f"- `{rel}`")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
