[project]
name = "provider-error-proxy"
version = "0.1.0"
description = "HTTP proxy for simulating provider errors in Goose"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.9.0",
    "brotli>=1.1.0",
]
