# This reusable workflow builds and packages the CLI for macOS.
on:
  workflow_call:
    inputs:
      version:
        required: false
        default: ""
        type: string
      ref:
        type: string
        required: false
        default: ""

name: "Reusable workflow to build CLI for macOS"

jobs:
  build-cli-macos:
    name: Build CLI
    runs-on: ${{ matrix.build-on }}
    env:
      MACOSX_DEPLOYMENT_TARGET: "12.0"
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64
            target-suffix: apple-darwin
            build-on: macos-15-intel
          - architecture: aarch64
            target-suffix: apple-darwin
            build-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Update version in Cargo.toml
        if: ${{ inputs.version != '' }}
        shell: bash
        env:
          VERSION: ${{ inputs.version }}
        run: bash scripts/set-cargo-version.sh "$VERSION"

      - name: Cache Cargo artifacts
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1
        with:
          key: ${{ matrix.architecture }}-${{ matrix.target-suffix }}-${{ matrix.build-on }}-native-macos-deployment-target-12

      - name: Build CLI
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
        run: |
          source ./bin/activate-hermit
          export TARGET="${{ matrix.architecture }}-${{ matrix.target-suffix }}"
          rustup target add "${TARGET}"
          echo "Building for target: ${TARGET}"
          echo "Rust toolchain info:"
          rustup show
          cargo build --release --target ${TARGET} -p goose-cli --bin goose

      - name: Package CLI
        run: |
          source ./bin/activate-hermit
          export TARGET="${{ matrix.architecture }}-${{ matrix.target-suffix }}"

          mkdir -p "target/${TARGET}/release/goose-package"
          cp "target/${TARGET}/release/goose" "target/${TARGET}/release/goose-package/"

          cd "target/${TARGET}/release"
          tar -cjf "goose-${TARGET}.tar.bz2" -C goose-package .
          tar -czf "goose-${TARGET}.tar.gz" -C goose-package .
          echo "ARTIFACT_BZ2=target/${TARGET}/release/goose-${TARGET}.tar.bz2" >> $GITHUB_ENV
          echo "ARTIFACT_GZ=target/${TARGET}/release/goose-${TARGET}.tar.gz" >> $GITHUB_ENV

      - name: Upload CLI artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: goose-${{ matrix.architecture }}-${{ matrix.target-suffix }}
          path: |
            ${{ env.ARTIFACT_BZ2 }}
            ${{ env.ARTIFACT_GZ }}
