# This is a **reuseable** workflow that bundles the Desktop App for Linux.
# It doesn't get triggered on its own. It gets used in multiple workflows:
#  - release.yml
#  - canary.yml (when added)
#  - pr-comment-bundle-desktop.yml (when added)
on:
  workflow_call:
    inputs:
      version:
        description: 'Version to set for the build'
        required: false
        default: ""
        type: string
      ref:
        type: string
        required: false
        default: 'refs/heads/main'

name: "Bundle Desktop (Linux)"

jobs:
  build-desktop-linux:
    name: Build Desktop (Linux)
    runs-on: ubuntu-latest

    steps:
      # 1) Check out source
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      # 2) Update versions before build
      - name: Update versions
        if: ${{ inputs.version != '' }}
        run: |
          # Update version in Cargo.toml
          sed -i.bak 's/^version = ".*"/version = "'${{ inputs.version }}'"/' Cargo.toml
          rm -f Cargo.toml.bak

          # Update version in package.json
          cd ui/desktop
          npm version ${{ inputs.version }} --no-git-tag-version --allow-same-version

      # 3) Debug information
      - name: Debug workflow info
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_REF: ${{ github.ref }}
          EVENT_NAME: ${{ github.event_name }}
          REPOSITORY: ${{ github.repository }}
        run: |
          echo "=== Workflow Information ==="
          echo "Workflow: ${WORKFLOW_NAME}"
          echo "Ref: ${WORKFLOW_REF}"
          echo "Event: ${EVENT_NAME}"
          echo "Repo: ${REPOSITORY}"
          echo ""
          echo "=== System Information ==="
          uname -a
          lsb_release -a || true
          df -h

      # 4) Install system dependencies for Linux packaging
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm2 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libxss1 \
            libasound2t64 \
            rpm \
            fakeroot \
            dpkg-dev \
            protobuf-compiler

      # 5) Set up Rust
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # 6) Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ui/desktop/package-lock.json

      # 7) Cache Rust dependencies
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index
          restore-keys: |
            ${{ runner.os }}-cargo-index

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      # 8) Build the Rust goosed binary
      - name: Build goosed binary
        run: |
          echo "Building goosed binary for Linux..."
          cargo build --release -p goose-server
          ls -la target/release/
          file target/release/goosed

      # 9) Clean up build artifacts to save space
      - name: Clean up build artifacts
        run: |
          echo "Cleaning up to save disk space..."
          # Remove debug artifacts
          rm -rf target/debug || true
          # Remove incremental build files
          rm -rf target/release/incremental || true
          rm -rf target/release/deps || true
          rm -rf target/release/build || true
          # Check disk space
          df -h

      # 10) Copy binary to Electron folder
      - name: Copy binary into Electron folder
        run: |
          echo "Copying goosed binary to ui/desktop/src/bin/"
          mkdir -p ui/desktop/src/bin
          cp target/release/goosed ui/desktop/src/bin/
          chmod +x ui/desktop/src/bin/goosed
          ls -la ui/desktop/src/bin/

      # 11) Install npm dependencies
      - name: Install npm dependencies
        run: |
          cd ui/desktop
          npm ci

      # 12) Build Electron app with Linux makers (.deb and .rpm)
      - name: Build Linux packages
        run: |
          cd ui/desktop
          echo "Building Linux packages (.deb and .rpm)..."
          
          # Build both .deb and .rpm packages
          npm run make -- --platform=linux --arch=x64
          
          echo "Build completed. Checking output..."
          ls -la out/
          find out/ -name "*.deb" -o -name "*.rpm" | head -10

      # 13) List all generated files for debugging
      - name: List generated files
        run: |
          echo "=== All files in out/ directory ==="
          find ui/desktop/out/ -type f | head -20
          echo ""
          echo "=== Package files specifically ==="
          find ui/desktop/out/ -name "*.deb" -o -name "*.rpm"
          echo ""
          echo "=== File sizes ==="
          find ui/desktop/out/ -name "*.deb" -o -name "*.rpm" -exec ls -lh {} \;

      # 14) Upload .deb package
      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: Goose-linux-x64-deb
          path: ui/desktop/out/make/deb/x64/*.deb
          if-no-files-found: error

      # 15) Upload .rpm package  
      - name: Upload .rpm package
        uses: actions/upload-artifact@v4
        with:
          name: Goose-linux-x64-rpm
          path: ui/desktop/out/make/rpm/x64/*.rpm
          if-no-files-found: error

      # 16) Create combined artifact with both packages
      - name: Upload combined Linux packages
        uses: actions/upload-artifact@v4
        with:
          name: Goose-linux-x64
          path: |
            ui/desktop/out/make/deb/x64/*.deb
            ui/desktop/out/make/rpm/x64/*.rpm
          if-no-files-found: error