name: Manual Desktop Bundle (Unsigned)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to bundle app from'
        required: true
        type: string

jobs:
  bundle-desktop-unsigned:
    uses: ./.github/workflows/bundle-macos.yml
    permissions:
      id-token: write
      contents: read
    with:
      target: aarch64-apple-darwin
      package_cli: false
      package_desktop: true
      signing: false
      ref: ${{ inputs.branch }}

  bundle-desktop-intel-unsigned:
    uses: ./.github/workflows/bundle-macos.yml
    permissions:
      id-token: write
      contents: read
    with:
      target: x86_64-apple-darwin
      package_cli: false
      package_desktop: true
      signing: false
      ref: ${{ inputs.branch }}
