name: Manual Desktop Bundle

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to bundle app from'
        required: true
        type: string
      signing:
        description: 'Whether to perform signing and notarization'
        required: false
        default: false
        type: boolean

jobs:
  bundle-desktop:
    uses: ./.github/workflows/bundle-desktop.yml
    permissions:
      id-token: write
      contents: read
    with:
      signing: ${{ inputs.signing }}
      ref: ${{ inputs.branch }}
      environment: ${{ inputs.signing && 'signing' || '' }}
    secrets: inherit

  bundle-desktop-intel:
    uses: ./.github/workflows/bundle-desktop-intel.yml
    permissions:
      id-token: write
      contents: read
    with:
      signing: ${{ inputs.signing }}
      ref: ${{ inputs.branch }}
      environment: ${{ inputs.signing && 'signing' || '' }}
    secrets: inherit
