name: Deploy Documentation

on:
  push:
    branches:
      - main
  
  pull_request:
    paths:
      - 'documentation/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 

      - name: Cache Node.js modules (documentation)
        uses: actions/cache@v3
        with:
          path: ./documentation/node_modules
          key: ${{ runner.os }}-documentation-${{ hashFiles('./documentation/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-documentation-

      - name: Install dependencies and build docs
        working-directory: ./documentation
        env:
          INKEEP_API_KEY: ${{ secrets.INKEEP_API_KEY }}
          INKEEP_INTEGRATION_ID: ${{ secrets.INKEEP_INTEGRATION_ID }}
          INKEEP_ORG_ID: ${{ secrets.INKEEP_ORG_ID }}
        run: |
          npm install
          npm run build

      - name: Deploy to /gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/build
