name: Publish GDK

on:
  pull_request:

permissions:
  contents: read

jobs:
  register-workflow:
    name: Register GDK release workflow
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Registering the GDK release workflow before enabling manual dispatch"
