---
name: License Check

on:
  pull_request: # Trigger license check on any PRs
    paths:
      - '**/pyproject.toml'
      - '.github/workflows/license-check.yml'
      - '.github/workflows/scripts/check_licenses.py'

  push: # Trigger license check on pushes to main
    branches:
      - main
    paths: # TODO: can't DRY unless https://github.com/actions/runner/issues/1182
      - '**/pyproject.toml'
      - '.github/workflows/license-check.yml'
      - '.github/workflows/scripts/check_licenses.py'

jobs:
  check-licenses:
    name: Check Package Licenses
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomli requests urllib3

      - name: Check licenses
        run: |
          python .github/workflows/scripts/check_licenses.py \
            pyproject.toml || exit_code=$?
          if [ "${exit_code:-0}" -ne 0 ]; then
            echo "::error::Found packages with disallowed licenses"
            exit 1
          fi

      - name: Check Exchange licenses
        run: |
          python .github/workflows/scripts/check_licenses.py \
            packages/exchange/pyproject.toml || exit_code=$?
          if [ "${exit_code:-0}" -ne 0 ]; then
            echo "::error::Found packages with disallowed licenses in exchange"
            exit 1
          fi
