name: Build Goose Release Candidate

on:
  pull_request:
    branches:
      - 'release/v[0-9].[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to comment on'
        required: true
        type: string
      ref:
        description: 'The ref to build'
        required: true
        type: string

jobs:
  bundle-desktop:
    uses: ./.github/workflows/bundle-desktop.yml
    with:
      signing: true
      ref: ${{ github.event.inputs && github.event.inputs.ref || '' }}

  comment-on-pr:
    needs: bundle-desktop
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Comment with download link
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # pin@v4
        with:
          issue-number: ${{ github.event.number || github.event.inputs.pr_number }}
          body: |
            ### macOS ARM64 Desktop App (Apple Silicon)

            [📱 Download macOS Desktop App (arm64, signed)](${{ needs.bundle-desktop.outputs.artifact-url }})

            **Instructions:**
            After downloading, unzip the file and drag the Goose.app to your Applications folder. The app is signed and notarized for macOS.
