on:
  pull_request: {}

name: Temp

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release manifest
        env:
          DOWNLOAD_URL: https://github.com/${{ github.repository }}/releases/latest/download
        run: |
          cat > manifest.json << EOF
          {
            "darwin": {
              "arm64": "${DOWNLOAD_URL}/goose.zip",
              "*": "${DOWNLOAD_URL}/goose_intel_mac.zip"
            },
            "win32": {
              "*": "${DOWNLOAD_URL}/goose-win32-x64.zip"
            }
          }
          EOF

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # pin@v4
        with:
          name: manifest.json
          path: manifest.json
